/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 32.0.1.Final (WildFly Core 24.0.1.Final) - 2.3.13.Final
 * Generated at: 2024-07-09 01:09:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class motorista_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private jakarta.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
        throws java.io.IOException, jakarta.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(jakarta.servlet.http.HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/3.1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"pt\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Motorista</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\" integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\" integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\" integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/root.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/global.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/table-page.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/modal.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/sidebar.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/inputs.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/buttons.css\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page-body\">\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/sidebar.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../components/table.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Modal de cadastro e edição-->\r\n");
      out.write("<div class=\"modal fade bd-example-modal-lg\" id=\"persistModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"header-modal-title\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"header-modal\">\r\n");
      out.write("                <h5 class=\"header-modal-title\" id=\"header-modal-title\"></h5>\r\n");
      out.write("                <button type=\"button\" class=\"header-modal-close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                    <svg aria-hidden=\"true\" width=\"35\" height=\"36\" viewBox=\"0 0 35 36\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                        <path d=\"M6.67196 7.17184C7.08218 6.76175 7.63848 6.53137 8.21853 6.53137C8.79857 6.53137 9.35487 6.76175 9.76509 7.17184L17.5001 14.9068L25.2351 7.17184C25.6477 6.77337 26.2002 6.55288 26.7738 6.55787C27.3473 6.56285 27.896 6.79291 28.3016 7.19849C28.7071 7.60407 28.9372 8.15272 28.9422 8.72628C28.9472 9.29983 28.7267 9.8524 28.3282 10.265L20.5932 18L28.3282 25.735C28.7267 26.1475 28.9472 26.7001 28.9422 27.2737C28.9372 27.8472 28.7071 28.3959 28.3016 28.8014C27.896 29.207 27.3473 29.4371 26.7738 29.4421C26.2002 29.4471 25.6477 29.2266 25.2351 28.8281L17.5001 21.0931L9.76509 28.8281C9.35252 29.2266 8.79995 29.4471 8.2264 29.4421C7.65284 29.4371 7.10419 29.207 6.69861 28.8014C6.29303 28.3959 6.06297 27.8472 6.05799 27.2737C6.05301 26.7001 6.27349 26.1475 6.67196 25.735L14.407 18L6.67196 10.265C6.26187 9.85475 6.03149 9.29845 6.03149 8.7184C6.03149 8.13836 6.26187 7.58206 6.67196 7.17184Z\" fill=\"#1C1C1C\" fill-opacity=\"0.5\"></path>\r\n");
      out.write("                    </svg>\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"body-modal\">\r\n");
      out.write("                <form action=\"motorista\" method=\"post\" class=\"body-modal-form\">\r\n");
      out.write("                    <h6 class=\"required-warning\">\r\n");
      out.write("                        Campos com<span class=\"required\">&nbsp;*&nbsp;</span>são obrigatórios!\r\n");
      out.write("                    </h6>\r\n");
      out.write("                    <div class=\"form-input-area\">\r\n");
      out.write("                        <input type=\"hidden\" value=\"\" name=\"operacao\" id=\"operacao\">\r\n");
      out.write("                        <input type=\"hidden\" value=\"\" name=\"cod\" id=\"cod\">\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <div class=\"input-wrapper-title\">\r\n");
      out.write("                                Identificação\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-wrapper-inputs\">\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <input class=\"input-text\" type=\"text\" id=\"nome\" name=\"nome\" maxlength=\"50\" required>\r\n");
      out.write("                                    <label class=\"input-label\" for=\"nome\"><span class=\"required\">*&nbsp;</span>Nome</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <input class=\"input-text\" type=\"text\" id=\"endereco\" name=\"endereco\" maxlength=\"100\">\r\n");
      out.write("                                    <label class=\"input-label\" for=\"endereco\">Endereco</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"input-wrapper\">\r\n");
      out.write("                            <div class=\"input-wrapper-title\">\r\n");
      out.write("                                Outros\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"input-wrapper-inputs\">\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <select id=\"caminhao\" class=\"input-select\"  name=\"caminhao\" >\r\n");
      out.write("                                        ");
      out.write("\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                    <label class=\"input-label\" for=\"caminhao\">Caminhão</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <input class=\"input-text\" type=\"text\" id=\"telefonePrincipal\" name=\"telefonePrincipal\" maxlength=\"15\" required>\r\n");
      out.write("                                    <label class=\"input-label\" for=\"telefonePrincipal\"><span class=\"required\">*&nbsp;</span>Telefone Principal</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <input class=\"input-text\" type=\"text\" id=\"telefoneAlternativo\" name=\"telefoneAlternativo\" maxlength=\"15\">\r\n");
      out.write("                                <label class=\"input-label\" for=\"telefoneAlternativo\">Telefone Alternativo</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"input-container\">\r\n");
      out.write("                                    <input class=\"input-text\" type=\"text\" id=\"telefoneAlternativo2\" name=\"telefoneAlternativo2\" maxlength=\"15\">\r\n");
      out.write("                                    <label class=\"input-label\" for=\"telefoneAlternativo2\">Telefone Alternativo 2</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <button type=\"submit\" class=\"cadastrar-button\"></button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-modal\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/table.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/input.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/sidebar.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const entidade = 'motorista';\r\n");
      out.write("    const tableTitleId = 'page-title';\r\n");
      out.write("    const tableHeadId = 'table-header';\r\n");
      out.write("    const tableBodyId = 'table-body';\r\n");
      out.write("    const incrementId = 'increment';\r\n");
      out.write("    const decrementId = 'decrement';\r\n");
      out.write("    const cols = [\r\n");
      out.write("        \"nome\",\r\n");
      out.write("        \"telefonePrincipal\",\r\n");
      out.write("        \"telefoneAlternativo\",\r\n");
      out.write("        \"telefoneAlternativo2\",\r\n");
      out.write("        \"endereco\"\r\n");
      out.write("    ];\r\n");
      out.write("    const colsNames = [\r\n");
      out.write("        \"Nome\",\r\n");
      out.write("        \"Telefone Principal\",\r\n");
      out.write("        \"Telefone Alternativo\",\r\n");
      out.write("        \"Telefone Alternativo 2\",\r\n");
      out.write("        \"Endereço\"\r\n");
      out.write("    ];\r\n");
      out.write("\r\n");
      out.write("    const maxItens = 15;\r\n");
      out.write("\r\n");
      out.write("    inicializarPagina(entidade, tableTitleId, tableHeadId, tableBodyId, cols, colsNames, maxItens);\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new jakarta.servlet.ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
