/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: WildFly Full 32.0.1.Final (WildFly Core 24.0.1.Final) - 2.3.13.Final
 * Generated at: 2024-07-10 23:22:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.components;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class delete_002dmodal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private jakarta.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
        throws java.io.IOException, jakarta.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(jakarta.servlet.http.HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/3.1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"modal fade bd-example-modal-lg\" id=\"deleteModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"delete-modal-title\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"header-modal\">\r\n");
      out.write("                <h5 class=\"header-modal-title\" id=\"delete-modal-title\">CONFIRMAR EXCLUSÃO</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"body-modal\">\r\n");
      out.write("                <h6 class=\"deleteWarning\">\r\n");
      out.write("                    Deseja mesmo excluir todos os dados do item atual? (Essa mudança é irreversível)\r\n");
      out.write("                </h6>\r\n");
      out.write("                <div class=\"cancel-delete-buttons\">\r\n");
      out.write("                    <a data-dismiss=\"modal\" id=\"cancelButton\">CANCELAR</a>\r\n");
      out.write("                    <a href=\"\" id=\"deleteButton\">\r\n");
      out.write("                        EXCLUIR\r\n");
      out.write("                        <svg width=\"19\" height=\"20\" viewBox=\"0 0 19 20\" fill=\"none\" xmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("                            <g id=\"material-symbols:delete\" clip-path=\"url(#clip0_760_2829)\">\r\n");
      out.write("                                <path id=\"Vector\" d=\"M3.88379 18.6316C3.29941 18.6316 2.79933 18.4359 2.38354 18.0446C1.96775 17.6533 1.7595 17.1823 1.75879 16.6316V3.63159H0.696289V1.63159H6.00879V0.631592H12.3838V1.63159H17.6963V3.63159H16.6338V16.6316C16.6338 17.1816 16.4259 17.6526 16.0101 18.0446C15.5943 18.4366 15.0939 18.6323 14.5088 18.6316H3.88379ZM6.00879 14.6316H8.13379V5.63159H6.00879V14.6316ZM10.2588 14.6316H12.3838V5.63159H10.2588V14.6316Z\" fill=\"#F3F3F3\"></path>\r\n");
      out.write("                            </g>\r\n");
      out.write("                            <defs>\r\n");
      out.write("                                <clipPath id=\"clip0_760_2829\">\r\n");
      out.write("                                    <rect width=\"18\" height=\"19\" fill=\"white\" transform=\"translate(0.5 0.5)\"></rect>\r\n");
      out.write("                                </clipPath>\r\n");
      out.write("                            </defs>\r\n");
      out.write("                        </svg>\r\n");
      out.write("\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-modal\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new jakarta.servlet.ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
